DEEPSORT:
  REID_CKPT: "models/deepsort/ckpt.t7"
  MAX_DIST: 0.4                          # Maximum cosine distance thold for similarity purpose
  MIN_CONFIDENCE: 0.4                    # Min confidence for entry bboxes 
  NMS_MAX_OVERLAP: 1                     # Remove boxes with overlap !! We don't want NMS, NMS already done and could destroy "Collision players"
  MAX_IOU_DISTANCE: 0.7                  # Gating IOU threshold. Associations with cost larger than this value are disregarded.
  MAX_AGE: 30                            # Maximum number of misses before a track is deleted. --> We prefer IDswitch rather that incorect re-ID
  N_INIT: 0                              # Number of consecutive detections before the track is confirmed. (0.1 s) The track state is set to `Deleted` if a miss occurs within the first `n_init` frames.
  NN_BUDGET: 100                         # If not None, fix samples per class to at most this number. Removes the oldest samples when the budget is reached.
